extends:
  - '@react-native-community'
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
rules:
  # typescript handles no-unused-vars
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - 'warn'
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
  '@typescript-eslint/no-non-null-assertion': off
